---
# Install Ansible so it can be run as a cron job
# Using http://docs.ansible.com/ansible/latest/intro_installation.html as reference
- name: pre-requirements | ansible
  apt: pkg=software-properties-common state=latest update-cache=yes

- name: add repository | ansible
  apt_repository: repo='ppa:ansible/ansible'

- name: install | ansible
  apt: pkg=ansible state=latest update-cache=yes

# Clone repository
- name: create git repository folder | ansible
  file:
    path: /srv/ansible
    state: directory
    mode: 0750
    owner: root
    group: root

- name: clone repository | ansible
  git:
    repo: 'https://github.com/kinow/nz-shiny-server.git'
    dest: /srv/ansible

- name: add cronjob | ansible
  cron:
    name: ansible_update
    special_time: hourly
    job: cd /srv/ansible
