---
- name: Install Packages
  apt: >
    pkg={{item}}
    state=installed
    update-cache=yes
  with_items:
    - nginx
    - spawn-fcgi
  tags:
    - nginx

- name: start nginx
  service: name=nginx state=started

- name: Disable default server
  file: path=/etc/nginx/sites-enabled/default state=absent
  tags:
    - nginx
  notify: reload nginx

- name: Copy R Shiny nginx site
  template: src=rshiny-site.j2 dest=/etc/nginx/sites-available/rshiny-site owner=root group=root mode=0644
  tags:
    - nginx
  notify: reload nginx

- name: Copy R Shiny HTTPS nginx site
  template: src=rshiny-site-https.j2 dest=/etc/nginx/sites-available/rshiny-site-https owner=root group=root mode=0644
  tags:
    - nginx
  notify: reload nginx

- name: Copy attribution logo
  copy: src=catalyst-logo.png dest=/usr/share/nginx/html/catalyst-logo.png

- name: Copy index HTML
  copy: src=index.html dest=/usr/share/nginx/html/index.html

- name: Enable R Shiny nginx site
  file: src="/etc/nginx/sites-available/rshiny-site"
        dest="/etc/nginx/sites-enabled/rshiny-site"
        owner=root
        group=root
        state=link
  tags:
    - nginx
  notify: reload nginx

- include_tasks: roles/nginx/tasks/letsencrypt.yml
  when: letsencrypt_enabled == true

- name: Enable R Shiny HTTPS nginx site
  file: src="/etc/nginx/sites-available/rshiny-site-https"
        dest="/etc/nginx/sites-enabled/rshiny-site-https"
        owner=root
        group=root
        state=link
  when: letsencrypt_enabled == true
  tags:
    - nginx
  notify: reload nginx

