---
- name: Download Shiny deb via wget
  command: /usr/bin/wget "{{ shiny_deb }}" -O shiny.deb
  args:
    chdir: "~"
    creates: ~/shiny.deb
  register: get_shiny

- name: Execute gdebi
  command: /usr/bin/gdebi -n ~/shiny.deb
  when: get_shiny.changed
  notify: 
    - restart nginx

- name: Copy attribution logo
  copy: src=catalyst-logo.png dest=/srv/shiny-server/catalyst-logo.png

- name: Copy index HTML
  copy: src=index.html dest=/srv/shiny-server/index.html
